# Generated by Django 4.2.17 on 2025-01-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teluskolearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
